fluentd:
  build: ./fluentd/
  ports:
   - "24224:24224"
  links:
   - "elasticsearch"
  volumes:
   - /Users/xu.yin/Desktop/EFK_demo/fluentd/:/fluentd/etc/
web1:
  build: ./web1/
  ports:
   - "80:80"
  links:
   - fluentd
  log_driver: "fluentd"
  log_opt:
    fluentd-address: "tcp://0.0.0.0:24224"
web2:
  build: ./web1/
  ports:
   - "8080:80"
  links:
   - fluentd
  log_driver: "fluentd"
  log_opt:
    fluentd-address: "tcp://0.0.0.0:24224"
web3:
  build: ./web1/
  ports:
   - "8070:80"
  links:
   - fluentd
  log_driver: "fluentd"
  log_opt:
    fluentd-address: "tcp://0.0.0.0:24224"
elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"
  expose:
    - 9200
kibana:
  image: kibana
  links:
   - "elasticsearch"
  ports:
   - "5601:5601"
